CREATE DATABASE cloud_robotics;

CREATE TABLE cloud_robotics_master (
    UNIQUE_ID VARCHAR(255) PRIMARY KEY,
    ROBOT_NAME VARCHAR(1000),
    LENGTH_M FLOAT(2),
    WIDTH_M FLOAT(2),
    HEIGHT_M FLOAT(2),
    SENSOR_TYPE VARCHAR(1000),
    IMAGE_URL TEXT);